services:

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/prometheus.yml
      - ./rules.yml:/rules.yml
    command:
      - --config.file=/prometheus.yml

  blackbox:
    image: quay.io/prometheus/blackbox-exporter
    restart: unless-stopped
    network_mode: "host"

  alertmanager:
    image: quay.io/prometheus/alertmanager
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./alertmanager.yml:/alertmanager.yml
    command:
      - --config.file=/alertmanager.yml