global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "A"
    static_configs:
      - targets: [ 'localhost:9100' ]
        labels:
          severity: "Info"
    metrics_path: '/probe'
    params:
      module: [ http_2xx ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
  - job_name: "Job B"
    static_configs:
      - targets: [ 'localhost:9101' ]
        labels:
          cachet_component: "B"
    metrics_path: '/probe'
    params:
      module: [ http_2xx ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
  - job_name: "C"
    static_configs:
      - targets: [ 'localhost:9102' ]
        labels:
          org: "special"
    metrics_path: '/probe'
    params:
      module: [ http_2xx ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

rule_files:
  - /rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

