services:
  adapter:
    build:
      context: .
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    ports:
      - "8002:8002"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8002/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

  load-components:
    build:
      context: .
    entrypoint:
      - uv
      - run
      - load-components
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    profiles:
      - migration

  load-dependency-graph:
    build:
      context: .
    entrypoint:
      - uv
      - run
      - load-dependencies
      - http://adapter:8002
    volumes:
      - ./data:/app/data
    depends_on:
      adapter:
        condition: service_healthy
    profiles:
      - migration

  load-schedules:
    build:
      context: .
    entrypoint:
      - uv
      - run
      - load-schedules
      - http://adapter:8002
    volumes:
      - ./data:/app/data
    depends_on:
      adapter:
        condition: service_healthy
    profiles:
      - cron

  sync-alerts:
    build:
      context: .
    entrypoint:
      - uv
      - run
      - sync-alerts
      - http://adapter:8002
    depends_on:
      adapter:
        condition: service_healthy
    profiles:
      - cron